services:

  converter1:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: mdconverter:latest
    container_name: converter1
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - proxy-network

  converter2:
    image: mdconverter:latest
    container_name: converter2
    ports:
      - "8082:80"
    restart: unless-stopped
    networks:
      - proxy-network

  converter3:
    image: mdconverter:latest
    container_name: converter3
    ports:
      - "8083:80"
    restart: unless-stopped
    networks:
      - proxy-network

  reverse-proxy:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    container_name: reverse-proxy
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - proxy-network
    depends_on:
      - converter1
      - converter2
      - converter3

networks:
  proxy-network:
    driver: bridge
