from __future__ import annotations

import argparse
import io
import json
import threading
import time
import zipfile
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from datetime import datetime
from typing import Dict

import requests


DEFAULT_TARGET = "http://localhost:8080/convert/md/to-pdf"


@dataclass
class Stats:
    started: int = 0
    completed: int = 0
    success: int = 0
    failed: int = 0
    status_2xx: int = 0
    status_4xx: int = 0
    status_5xx: int = 0
    total_latency_s: float = 0.0


def create_zip_payload() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            "report.md",
            "# Load Test\n\nThis request is generated by load script.\n\n- Item 1\n- Item 2\n",
        )
    return buf.getvalue()


def classify_status(code: int, stats: Stats) -> None:
    if 200 <= code < 300:
        stats.status_2xx += 1
    elif 400 <= code < 500:
        stats.status_4xx += 1
    elif 500 <= code < 600:
        stats.status_5xx += 1


def worker(
    target_url: str,
    timeout_s: float,
    end_time: float,
    zip_payload: bytes,
    stats: Stats,
    lock: threading.Lock,
) -> None:
    files = {"archive": ("load_test.zip", io.BytesIO(zip_payload), "application/zip")}

    while time.time() < end_time:
        start = time.perf_counter()

        with lock:
            stats.started += 1

        status_code = 0
        success = False
        try:
            # Rewind buffer before each request because requests will read it.
            files["archive"][1].seek(0)
            response = requests.post(
                target_url,
                files=files,
                timeout=timeout_s,
                headers={"User-Agent": "least-connections-loadgen/1.0"},
            )
            status_code = int(response.status_code)
            success = response.ok
        except requests.RequestException:
            status_code = 0
        finally:
            latency = time.perf_counter() - start
            with lock:
                stats.completed += 1
                stats.total_latency_s += latency
                if success:
                    stats.success += 1
                else:
                    stats.failed += 1
                if status_code != 0:
                    classify_status(status_code, stats)


def snapshot(stats: Stats, started_at: float) -> Dict[str, float | int]:
    elapsed = max(time.time() - started_at, 1e-9)
    avg_latency_ms = (stats.total_latency_s / stats.completed * 1000.0) if stats.completed else 0.0
    rps = stats.completed / elapsed
    return {
        "elapsed_s": elapsed,
        "started": stats.started,
        "completed": stats.completed,
        "success": stats.success,
        "failed": stats.failed,
        "status_2xx": stats.status_2xx,
        "status_4xx": stats.status_4xx,
        "status_5xx": stats.status_5xx,
        "avg_latency_ms": avg_latency_ms,
        "rps": rps,
    }


def print_live(snapshot_data: Dict[str, float | int]) -> None:
    now = datetime.now().strftime("%H:%M:%S")
    print(
        f"[{now}] "
        f"done={snapshot_data['completed']} "
        f"ok={snapshot_data['success']} "
        f"err={snapshot_data['failed']} "
        f"2xx={snapshot_data['status_2xx']} "
        f"4xx={snapshot_data['status_4xx']} "
        f"5xx={snapshot_data['status_5xx']} "
        f"avg={snapshot_data['avg_latency_ms']:.1f}ms "
        f"rps={snapshot_data['rps']:.2f}"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate concurrent load for reverse proxy endpoint.")
    parser.add_argument("--url", default=DEFAULT_TARGET, help=f"Target URL (default: {DEFAULT_TARGET})")
    parser.add_argument("--concurrency", type=int, default=10, help="Number of parallel workers (default: 10)")
    parser.add_argument("--duration", type=int, default=30, help="Test duration in seconds (default: 30)")
    parser.add_argument("--timeout", type=float, default=15.0, help="Per-request timeout in seconds (default: 15)")
    parser.add_argument(
        "--progress-interval",
        type=float,
        default=1.0,
        help="How often to print live stats in seconds (default: 1)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print final summary as JSON",
    )
    args = parser.parse_args()

    if args.concurrency <= 0:
        parser.error("--concurrency must be > 0")
    if args.duration <= 0:
        parser.error("--duration must be > 0")
    if args.timeout <= 0:
        parser.error("--timeout must be > 0")
    if args.progress_interval <= 0:
        parser.error("--progress-interval must be > 0")

    return args


def main() -> None:
    args = parse_args()

    zip_payload = create_zip_payload()

    stats = Stats()
    lock = threading.Lock()

    started_at = time.time()
    end_time = started_at + args.duration

    print("Starting load test")
    print(f"- URL: {args.url}")
    print(f"- Concurrency: {args.concurrency}")
    print(f"- Duration: {args.duration}s")
    print(f"- Timeout: {args.timeout}s")
    print("- Payload: single markdown file in zip archive")
    print("=" * 72)

    with ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        futures = [
            pool.submit(
                worker,
                args.url,
                args.timeout,
                end_time,
                zip_payload,
                stats,
                lock,
            )
            for _ in range(args.concurrency)
        ]

        while time.time() < end_time:
            time.sleep(args.progress_interval)
            with lock:
                snap = snapshot(stats, started_at)
            print_live(snap)

        for future in futures:
            future.result()

    with lock:
        final = snapshot(stats, started_at)

    print("=" * 72)
    if args.json:
        print(json.dumps(final, indent=2))
    else:
        print("Final summary")
        print(f"- Elapsed: {final['elapsed_s']:.2f}s")
        print(f"- Started: {final['started']}")
        print(f"- Completed: {final['completed']}")
        print(f"- Success: {final['success']}")
        print(f"- Failed: {final['failed']}")
        print(f"- 2xx: {final['status_2xx']}, 4xx: {final['status_4xx']}, 5xx: {final['status_5xx']}")
        print(f"- Avg latency: {final['avg_latency_ms']:.2f} ms")
        print(f"- Throughput: {final['rps']:.2f} req/s")


if __name__ == "__main__":
    main()
